### ISSUE TITLE
Support Conan 2

### ISSUE THREAD

**Issue by nilanjan** [aminya/project_options#212] opened 2023-04-24 03:38 UTC
I am trying to enable conan and facing the following error. Also can I get conan_extra_options?

-- Conan: Adding conancenter remote repository (https://center.conan.io/) verify ssl (True)
-- Configuring incomplete, errors occurred!

![](https://user-images.githubusercontent.com/512388/233793358-3d3d653e-f51c-4e53-90d4-535961da41b2.png)

## Upvote & Fund

- I am using [Polar.sh](https://polar.sh/aminya) so you can upvote and help fund this issue. The funding is received once the issue is completed & confirmed by you.

- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/aminya/project_options/issues/212">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/aminya/project_options/issues/212/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/aminya/project_options/issues/212/pledge.svg">
</picture>
</a>

**Comment by aminya** [comment] 2023-04-24 04:16
This cannot be reproduced inside CI. Can you provide a minimal reproducible example? What version of Conan do you have installeD?

**Comment by nilanjan** [comment] 2023-04-24 04:33
I am on macOS ventura. Conan version 2.0.4. Conan is installed n a python virtual env. No conan profile is setup. 
<img width="1073" alt="Screenshot 2023-04-23 at 9 33 15 PM" src="https://user-images.githubusercontent.com/512388/233900625-3176ec0a-9265-4f91-a013-70922f536eb1.png">

**Comment by nilanjan** [comment] 2023-04-24 04:35
MacOS 13.3.1 on M1 Max machine.

**Comment by FeignClaims** [comment] 2023-04-25 02:47
The official cmake support for conan 2.0 is experimental (see the README in [conan-io/cmake-conan](https://github.com/conan-io/cmake-conan/tree/develop2)). Also, this repo hasn't update to the conan 2.0 version.

The way you use conan 2.0 with this repo for now, is to disable it in project_options options and run conan separately (see [conan 2.0 tutorial](https://docs.conan.io/2/tutorial.html) for help if you need).

[My conan 2.0 template](https://github.com/FeignClaims/cmake_starter_template) might help, but I documented it badly.

**Comment by nilanjan** [comment] 2023-04-27 05:54
@FeignClaims It was really helpful for most of the things other than google test. Do you have setup for the google test somewhere?

**Comment by FeignClaims** [comment] 2023-04-27 07:51
> @FeignClaims Do you have setup for the google test somewhere?

By running `conan install  . -b missing`, conan should install google test for you. I configured it in conanfile.py as `test_requires` in the section `build_requirements()`, which is [a dedicated place to define `tool_requires` and `test_requires`](https://docs.conan.io/2/reference/conanfile/methods/build_requirements.html).

**Comment by FeignClaims** [comment] 2023-04-27 08:38
> > @FeignClaims Do you have setup for the google test somewhere?
> 
> conan should install google test for you.

My bad. My simple configuration `gtest/[>=1.13.0]` makes conan to choose `gtest/cci.20210126` instead of the versioned gtest, and `gtest/cci.20210126` works differently. Fixed by replacing it with `gtest/1.13.0`.

**Comment by aminya** [comment] 2023-07-21 17:18
Conan 2 support is still experimental. Not sure if we should start adding it to project_options yet. There are also some issues with the latest released version (See #184)

Windows tests with LLVM and MSVC fail to build. Seems to be related to:
https://github.com/conan-io/cmake-conan/issues/459
https://github.com/conan-io/cmake-conan/issues/455
https://github.com/conan-io/cmake-conan/pull/454

**Comment by aminya** [comment] 2023-11-14 06:11
Is there anyone interested in integrating CMake Conan 2? Contributions are welcome.

**Closed** 2024-02-25 10:28 UTC
Labels: enhancement, pr-welcome
