### ISSUE TITLE
After 0.26, cmake configuration has fail with 'Unable identify compiler architecture for CMAKE_SYSTEM_PROCESSOR'

### ISSUE THREAD

**Issue by hihig2001** [aminya/project_options#200] opened 2023-01-31 10:30 UTC
I think changes affects to my project is [this](https://github.com/aminya/project_options/pull/168).
My project is fine until v0.25.2.

I use visual studio 2022 17.4.4 with integrated cmake, and pre-installed vcpkg.
My cmake file is mostly similar with [example file](https://github.com/aminya/cpp_vcpkg_project/blob/main/CMakeLists.txt).
Difference is that I don't use `run_vcpkg()` functionality.
Instead, I register 'CMAKE_TOOL_CHAIN' using CMakePresets.json, just like visual studio's [official manual](https://learn.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-170#enable-vcpkg-integration).

I'm not so sure about that it is appropriate to report here or '[WindowsToolchain](https://github.com/MarkSchofield/WindowsToolchain)' cause it is dependency not 'project_option' itself.
but I thought that it is something worth to report.

```
1> Command line: "C:\WINDOWS\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_TOOLCHAIN_FILE:FILEPATH="C:\dev\vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_C_COMPILER:STRING="cl" -DCMAKE_CXX_COMPILER:STRING="cl" -DCMAKE_BUILD_TYPE:STRING="Debug" -DFEATURE_UNIT_TESTS:STRING="ON" -DCMAKE_INSTALL_PREFIX:PATH="E:/work/Knuckles/Game/out/install/windows-msvc-debug-soft-mode"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "E:\work\Knuckles\Game" 2>&1"
1> Working directory: E:/work/Knuckles/Game/out/build/windows-msvc-debug-soft-mode
1> [CMake] CMake Warning (dev) at C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1264 (message):
1> [CMake]   The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
1> [CMake]   not set.  The policy's OLD behavior will be used.  When using a URL
1> [CMake]   download, the timestamps of extracted files should preferably be that of
1> [CMake]   the time of extraction, otherwise code that depends on the extracted
1> [CMake]   contents might not be rebuilt if the URL changes.  The OLD behavior
1> [CMake]   preserves the timestamps from the archive instead, but this is usually not
1> [CMake]   what you want.  Update your project to the NEW behavior or specify the
1> [CMake]   DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
1> [CMake]   robustness issue.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:24 (FetchContent_Declare)
1> [CMake] This warning is for project developers.  Use -Wno-dev to suppress it.
1> [CMake] 
1> [CMake] -- Using Windows Windows toolchain
1> [CMake] CMake Error at out/build/windows-msvc-debug-soft-mode/_deps/_msvc_toolchain-src/Windows.MSVC.toolchain.cmake:169 (message):
1> [CMake]   Unable identify compiler architecture for CMAKE_SYSTEM_PROCESSOR
1> [CMake] Call Stack (most recent call first):
1> [CMake]   out/build/windows-msvc-debug-soft-mode/_deps/_project_options-src/src/VCEnvironment.cmake:72 (include)
1> [CMake]   out/build/windows-msvc-debug-soft-mode/_deps/_project_options-src/src/Index.cmake:34 (msvc_toolchain)
1> [CMake]   out/build/windows-msvc-debug-soft-mode/_deps/_project_options-src/CMakeLists.txt:3 (include)
1> [CMake] -- Configuring incomplete, errors occurred!
1> 'C:\WINDOWS\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_TOOLCHAIN_FILE:FILEPATH="C:\dev\vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_C_COMPILER:STRING="cl" -DCMAKE_CXX_COMPILER:STRING="cl" -DCMAKE_BUILD_TYPE:STRING="Debug" -DFEATURE_UNIT_TESTS:STRING="ON" -DCMAKE_INSTALL_PREFIX:PATH="E:/work/Knuckles/Game/out/install/windows-msvc-debug-soft-mode"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "E:\work\Knuckles\Game" 2>&1"' execution failed with error: ''C:\WINDOWS\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_TOOLCHAIN_FILE:FILEPATH="C:\dev\vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_C_COMPILER:STRING="cl" -DCMAKE_CXX_COMPILER:STRING="cl" -DCMAKE_BUILD_TYPE:STRING="Debug" -DFEATURE_UNIT_TESTS:STRING="ON" -DCMAKE_INSTALL_PREFIX:PATH="E:/work/Knuckles/Game/out/install/windows-msvc-debug-soft-mode"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "E:\work\Knuckles\Game" 2>&1"' returned with exit code: 1'.
```

**Comment by abeimler** [comment] 2023-02-01 06:19
I have the same problem with my Windows 10 and visual studio 2022 17.  
Tried to move the `include(${_project_options_SOURCE_DIR}/Index.cmake)` under the `project()` (so it could find the `CMAKE_SYSTEM_PROCESSOR`), but got some other error...

My workaround right now is just not using `CMakePresets.json`.

**Comment by hihig2001** [comment] 2023-02-01 06:26
My workaround is using v0.25.2 :)

**Comment by aminya** [comment] 2023-02-01 06:39
I don't understand the root of the problem. Why is the value of `CMAKE_SYSTEM_PROCESSOR` not given in the logs? Is it a string?

**Comment by hihig2001** [comment] 2023-02-01 06:49
I found difference in log.
In v0.25.2
``` -- Using Windows MSVC toolchain ```
after v0.26.x
``` -- Using Windows Windows toolchain ```
maybe it is related issue I don't know. 🤷

**Comment by aminya** [comment] 2023-02-01 06:51
I have reported the issue upstream.

**Comment by hihig2001** [comment] 2023-02-01 06:53
Thanks a lot :D

**Comment by Nosenzor** [comment] 2023-02-13 15:41
Also found that using CLION you may have to check that the compiler is pointing to the right version of "cl" (there's two cl installed one for x32 and other one for x64).
like this C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe
Setting project_option to v25 and resetting this seems to fix the problem (quite odd)

**Comment by Nosenzor** [comment] 2023-08-09 09:08
Issue reproduced today with 0.31 on Windows 
```
- Using Windows Windows toolchain
CMake Error at cmake-build-release/_deps/_msvc_toolchain-src/Windows.MSVC.toolchain.cmake:166 (message):
  **Unable identify compiler architecture for CMAKE_SYSTEM_PROCESSOR**
Call Stack (most recent call first):
  cmake-build-release/_deps/_project_options-src/src/VCEnvironment.cmake:65 (include)
  cmake-build-release/_deps/_project_options-src/src/Index.cmake:38 (msvc_toolchain)
  cmake-build-release/_deps/_project_options-src/CMakeLists.txt:3 (include)
```

while version 0.25.2 correctly set this variable :

```
-- Running vcpkg install - done
BUILD TYPE : Release USING :MSVC version : 19.36.32537.0
CMAKE_SYSTEM_PROCESSOR = x64
CMAKE_SYSTEM_NAME = Windows
CMAKE_SYSTEM_VERSION = 
CMAKE_SYSTEM = Windows
CMAKE_CXX_COMPILER = C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe
CMAKE_CXX_COMPILER_VERSION = 19.36.32537.0
CMAKE_CXX_COMPILER_ID = MSVC
CMAKE_CXX_COMPILER_FRONTEND_VARIANT = MSVC
CMAKE_CXX_COMPILER_TARGET = 
CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN = 
CMAKE_CXX_COMPILER_LAUNCHER = 
CMAKE_CXX_COMPILER_WORKS = TRUE
```

**Comment by Nosenzor** [comment] 2023-08-21 16:46
0.32 does not fix this issue, but here is what I discovered after debugging a bit.
I think the issue is in the generator issue, maybe related to CLION.
If I run cmake like this **please notice the -G option**, then it works fine :
`"C:\Program Files\JetBrains\CLion 2023.2\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "CodeBlocks - MinGW Makefiles" -S C:\Users\Shadow\CLionProjects\PhotoTools -B C:\Users\Shadow\CLionProjects\PhotoTools\cmake-build-relwithdebinfo-mingw"
`

 
While if I run it like this it does not work (the issue, here), note that's how Clion is setting the Generator by default :
`"C:\Program Files\JetBrains\CLion 2023.2\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - NMake Makefiles" -S C:\Users\Shadow\CLionProjects\PhotoTools -B C:\Users\Shadow\CLionProjects\PhotoTools\cmake-build-release`
Removing the "-G" (ie let's cmake decide what generator to use) like this also lead to the issue : 
`"C:\Program Files\JetBrains\CLion 2023.2\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Release -S C:\Users\Shadow\CLionProjects\PhotoTools -B C:\Users\Shadow\CLionProjects\PhotoTools\cmake-build-release`


And this works too : 
`"C:\Program Files\JetBrains\CLion 2023.2\bin\cmake\win\x64\bin\cmake.exe" -G "Visual Studio 17 2022" -S C:\Users\Shadow\CLionProjects\PhotoTools -B C:\Users\Shadow\CLionProjects\PhotoTools\cmake-build-debug`

So it sounds there's a combination of Generator/platform (windows) that lead to the issue, not sure it is a project_options issue

**Comment by aminya** [comment] 2023-08-21 18:01
Now, that I look at this again, I noticed that I didn't use `CMAKE_TOOLCHAIN_FILE` as the variable to bypass the MSVC toolchain. That might be why it doesn't fix the issue.

Could you try editing `build/_deps/project_options-src/src/Index.cmake` line 38 to see if it fixes it?

**Comment by aminya** [comment] 2023-08-21 18:13
> 0.32 does not fix this issue, but here is what I discovered after debugging a bit. I think the issue is in the generator issue, maybe related to CLION. If I run cmake like this **please notice the -G option**, then it works fine.

Not specifying `-G` on Windows means it uses the `Visual Studio*` generator, which I specifically guard against. Maybe `CMAKE_GENERATOR` is not set yet at that point. 

https://github.com/aminya/project_options/blob/90b064b55f787b886c7b912727c8171cda8e8116/src/VCEnvironment.cmake#L53

**Comment by Nosenzor** [comment] 2023-08-22 10:34
> Now, that I look at this again, I noticed that I didn't use `CMAKE_TOOLCHAIN_FILE` as the variable to bypass the MSVC toolchain. That might be why it doesn't fix the issue.
> 
> Could you try `v0.32.1` and see if it fixes the issue?

Hey, very happy to help here so tested with **0.32.1** on windows, mac and linux. **The good news is no more issue** ! Well done !
BTW I suggest you try to automate test (like trying to build your example) using github actions on the three platforms FYI, I'm using project options with [Lukka's vcpkg](https://github.com/lukka/run-vcpkg)

**Comment by aminya** [comment] 2023-08-22 18:40
Awesome! Closing this then

**Closed by aminya** 2023-08-22 18:40 UTC

**Comment by aminya** [comment] 2023-08-22 18:42
> BTW I suggest you try to automate test (like trying to build your example) using github actions on the three platforms FYI, I'm using project options with [Lukka's vcpkg](https://github.com/lukka/run-vcpkg)

We already have a very comprehensive CI suite. We use [`setup-cpp`](https://github.com/aminya/setup-cpp).

https://github.com/aminya/project_options/actions
![image](https://github.com/aminya/project_options/assets/16418197/a8e865c2-6d68-48de-8e24-d8db23ae70e4)
![image](https://github.com/aminya/project_options/assets/16418197/2dac0967-a2a0-40b7-b717-cdbdc8f22f14)
