### ISSUE TITLE
Allow to specify a GitHub mirror for dependencies

### ISSUE THREAD

**Issue by maximiliank** [aminya/project_options#145] opened 2022-08-22 20:38 UTC
Currently the dependencies (fargs, ycm, conan) are fetched from github. Unfortunately, this does not work in environments where github is only accessible via a mirror. Would it be possible to somehow parameterize the github mirror for these dependencies?

Or is it only possible to appy a patch to replace the dependent urls when calling FetchContent_Declare?

**Comment by aminya** [comment] 2022-08-22 23:55
Couldn't you forward GitHub URLs on your side? Not having access to GitHub is unfortunate as many tools (not just project_options) rely on it.

PRs for adding options for the mirrors are welcome. It might be easier to maintain a fork with your special mirrors.

**Comment by maximiliank** [comment] 2022-08-23 18:25
I also tried to forward it via /etc/hosts file, but I could not mange to forward https://github.com -> https://mycompany.corp/github-proxy/mirror/. As you mentioned, no access to GitHub complicate a lot of things. Do you have any suggestions how the forwarding would be possible on a linux machine?

I will think about a mirror option in case I cannot work out the forwarding.

**Comment by ClausKlein** [comment] 2022-08-25 17:43
you may try this: https://github.com/cpm-cmake/CPM.cmake#private-repositories-and-ci

**Comment by maximiliank** [comment] 2022-08-31 14:06
Thanks for the link. But this works only for git right?
And I think
`FetchContent_Declare(_ycm URL https://github.com/robotology/ycm/archive/refs/tags/v0.13.0.zip)`
does not use git.

**Comment by aminya** [comment] 2022-09-01 20:13
Take a look at this discussion. It shows how you can forward URLs in Linux
https://stackoverflow.com/questions/35370967/redirect-local-url-to-another-url

**Comment by ClausKlein** [comment] 2022-09-15 11:00
Sorry, our company rules are: **no internet access on CI build.**

this does not work on windows for us: https://github.com/aminya/project_options/blob/main/src/VCEnvironment.cmake#L70

Is this really necessary to use `FetchContents`?
Would it be possible to use `CMP.cmake`?

We have a local git mirror with selected git repos while build our SW projects on our CI.

**Comment by ClausKlein** [comment] 2022-09-16 03:30
> Take a look at this discussion. It shows how you can forward URLs in Linux
> https://stackoverflow.com/questions/35370967/redirect-local-url-to-another-url

@aminya This is not an option for because of our company rules!

**Comment by aminya** [comment] 2022-09-16 07:12
> This is not an option because of our company rules!

Your company rules are too strict. You would have a better chance to spawn a local HTTP server that returns your local files.

**Comment by aminya** [comment] 2022-09-16 07:12
I am closing this issue as it is not related to project_options or any other tool that uses the internet. You have to fix the issues with proxy, forwarding, or local servers on your side.

**Closed by aminya** 2022-09-16 07:12 UTC

**Comment by ClausKlein** [comment] 2022-09-16 18:51
> I am closing this issue as it is not related to project_options or any other tool that uses the internet.

Sorry, it is related to your project!

**This extremely limit the usability of this project.**

I am searching for a solution:
- you may not fetch zip archives but clone git repositories
- you may use `CPM.cmake` to fetch git repos and we may fill the [CPM_SOURCE_CACHE](https://github.com/cpm-cmake/CPM.cmake#cpm_source_cache)
- you may document and supports for each external package you net to fetch the `<dependency>_SOURCE_DIR`  cmake variable, which is the path to the source of the dependency already installed on CI

The `CMP.cmake` [package-lock](https://github.com/cpm-cmake/CPM.cmake#package-lock) is in general a good idea to have control, which external dependency are used while build!

**Comment by ClausKlein** [comment] 2022-09-16 19:44
@aminya see https://github.com/ClausKlein/project_options/pull/5

**Comment by aminya** [comment] 2022-09-16 19:44
Well, the way you emulate the internet is not sufficient. Local git repositories are just a very small part of the internet. You should run a local HTTPS server that returns other parts of the internet like the zip files.

The whole point of modern package managers like vcpkg and Conan is to not rely on the Git repositories that are slow, untested, mutable, and error-prone.

**Comment by ClausKlein** [comment] 2022-09-16 19:55
I am not a friend of having such restrictions!
Our IT is given and may not changed or extended.

But we must have control what is need to build our SW.
We have to document and archive everything. (source, tools, build scripts, licence, ..)
And we want to reproduce a build if needed.

And, I like to be able to compile with my local cache, too if my internet is down.

**Comment by aminya** [comment] 2022-09-17 03:56
The original issue is about Conan, which uses the internet (not git). The only solution to emulate the internet locally is to run a DNS server as I explained in
https://github.com/aminya/project_options/issues/145#issuecomment-1249742470

Still, both problems are out of scope.

**Comment by ClausKlein** [comment] 2022-09-17 10:54
@lefticus @aminya The problem is common and perhaps solved bye `CMake v3.24`

[dependency-providers](https://cmake.org/cmake/help/latest/command/cmake_language.html#dependency-providers)
